# Generated by Django 2.0 on 2020-11-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201128_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(default='NOT AVAIALBE', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='district',
            field=models.CharField(default='NOT AVAIALBE', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='state',
            field=models.CharField(default='NOT AVAIALBE', max_length=255),
        ),
    ]
