# Generated by Django 2.0 on 2020-11-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='upi_id',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
