# Generated by Django 2.0 on 2020-11-29 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_doctor_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='problem',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
