# Generated by Django 3.1.4 on 2020-12-29 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201229_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
