# Generated by Django 3.1.4 on 2020-12-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_doctor_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment',
            field=models.IntegerField(default=500, null=True),
        ),
    ]
